
name: Visit With Us MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  validate-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate dataset
        run: |
          python src/validate_data.py

  prepare-and-train:
    needs: validate-data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/train_model.py

      - name: Upload train-test artifact
        uses: actions/upload-artifact@v4
        with:
          name: train-test-data
          path: artifacts/

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/tourism_purchase_model.pkl

  commit-model:
    needs: prepare-and-train
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: models/

      - name: Commit updated model
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add models/tourism_purchase_model.pkl

          git diff --cached --quiet || \
          git commit -m "Automated model update"

          git push
